# Generated by Django 5.0.3 on 2024-04-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('color', models.TextField(max_length=50)),
                ('talla', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
    ]
